name: CI - Pruebas Unitarias

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Instalar PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Ejecutar pruebas unitarias
        working-directory: telefonica
        run: php phpunit.phar --coverage-text
